### PR TITLE
Removed guava from dependencies

### LINKED ISSUE #56: [kapt] NoClassDefFoundError after updating to 2.0.1
After updating library version to 2.0.1 we will (or can) get compilation error:

```
[kapt] An exception occurred: java.lang.NoClassDefFoundError: com/google/common/base/Preconditions
  at moxy.compiler.Util.equalsBy(Util.java:229)
  at moxy.compiler.viewstate.ViewMethod.equals(ViewMethod.java:144)
  at java.util.ArrayList.indexOf(ArrayList.java:321)
  at java.util.ArrayList.contains(ArrayList.java:304)
  at moxy.compiler.viewstate.ViewInterfaceProcessor.getMethods(ViewInterfaceProcessor.java:187)
  at moxy.compiler.viewstate.ViewInterfaceProcessor.iterateInterfaces(ViewInterfaceProcessor.java:257)
  at moxy.compiler.viewstate.ViewInterfaceProcessor.process(ViewInterfaceProcessor.java:87)
  at moxy.compiler.viewstate.ViewInterfaceProcessor.process(ViewInterfaceProcessor.java:29)
  at moxy.compiler.MvpCompiler.generateCode(MvpCompiler.kt:172)
  at moxy.compiler.MvpCompiler.throwableProcess(MvpCompiler.kt:108)
  at moxy.compiler.MvpCompiler.process(MvpCompiler.kt:66)
  at 
```
As we can se from the logs, `moxy-compiler` uses `Guava` dependency, `Preconditions` class is used in `Util.equalsBy()` method `(Util.java:229)` But for some reasons, this dependency can't be resolved in consumer application.

Dependencies used:

```
implementation "com.github.moxy-community:moxy:2.0.1"
implementation "com.github.moxy-community:moxy-androidx:2.0.1"
kapt "com.github.moxy-community:moxy-compiler:2.0.1"
```

Possible workaround is to add `Guava` to your project:

`implementation "com.google.guava:guava:23.0"`

After this, if you have no any other `Guava` dependencies in your project, everything will works fine, BUT if you are using some libraries that have internal dependency to some other version of `Guava` you can get something like this (or similar):

`Cause 1: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.RuntimeException: Duplicate class com.google.common.util.concurrent.ListenableFuture found in modules guava-23.0.jar (com.google.guava:guava:23.0) and listenablefuture-1.0.jar (com.google.guava:listenablefuture:1.0) `

In this case you will need to resolve conflicts between different `Guava` versions.

### PR DESCRIPTION
**Pull request by asitnkova**
Closes #56

### CODE REVIEW

File: moxy-compiler/src/main/java/moxy/compiler/Util.java [hunk 1]
```diff
@@ -224,9 +225,8 @@ public static String decapitalizeString(String string) {
     public static <T> boolean equalsBy(
         Collection<T> first,
         Collection<T> second,
-        BiFunction<T, T, Boolean> predicate) {
+        @NotNull BiFunction<T, T, Boolean> predicate) {
```
Comment (alaershov) [inline moxy-compiler/src/main/java/moxy/compiler/Util.java]: You've removed an explicit runtime check, and if predicate is null, this will crash with a non-obvious NPE. Maybe just write this precondition manually?

Comment (asitnkova) [reply moxy-compiler/src/main/java/moxy/compiler/Util.java]: It is used internally by library in single place, annotation will warn about this parameter being not null. And it had no precondition check for long time, it was added in one of the recent PRs. So i dont think there should be any check

File: moxy-compiler/src/main/java/moxy/compiler/Util.java [hunk 2]
```diff
@@ -16,7 +16,8 @@
  */
 package moxy.compiler;
 
-import com.google.common.base.Preconditions;
+import org.jetbrains.annotations.NotNull;
```
[the remark this answers is not in the document]
Comment (asitnkova) [reply moxy-compiler/src/main/java/moxy/compiler/Util.java]: Compiler already have dependency on kotlin, and this dependency wont get into library
